services:
  db:
    image: postgres:17
    container_name: cadastro_dev_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7KTu)%7
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

app:
    build: .
    container_name: cadastro_dev_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 7KTu)%7
      DB_NAME: postgres
    volumes:
      - .:/usr/src/app
volumes:
  postgres_data: